language: node_js

os: linux

cache: false

node_js:
  - "8"
  - "node"

before_script:
  - export DEPS=$(node -e "const deps=require('./package.json').peerDependencies;console.log(Object.keys(deps).map(key=>key+'@'+deps[key]).join(' '));")
  - npm install $DEPS

script:
  - echo "Running tests against $(node -v) ..."
  - npm run lint

jobs:
  include:
    - stage: github pages
      node_js: "10"
      git:
        clone: false
      script:
        - echo "Publish site to github pages ..."
        - git clone --recurse-submodules https://github.com/ppoffice/hexo-theme-icarus.git -b site $TRAVIS_BUILD_DIR
        - cd $TRAVIS_BUILD_DIR/themes/icarus
        - git fetch origin $TRAVIS_COMMIT && git merge $TRAVIS_COMMIT
        - export DEPS=$(node -e "const deps=require('./package.json').peerDependencies;console.log(Object.keys(deps).map(key=>key+'@'+deps[key]).join(' '));")
        - cd $TRAVIS_BUILD_DIR
        - npm install -g hexo-cli
        - npm install
        - npm install $DEPS
        - cp _config.theme.yml themes/icarus/_config.yml
        - hexo g
      deploy:
        provider: pages
        token: $GITHUB_TOKEN
        keep_history: false
        local_dir: public
        skip_cleanup: true
        on:
          tags: true

    - stage: github release
      node_js: "10"
      script: echo "Deploying to github release ..."
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        on:
          tags: true
