blank_issues_enabled: false
contact_links:
  - name: Gitter
    url: https://gitter.im/hexo-theme-icarus/community
    about: Redirect your Icarus usage questions to Gitter.
  - name: Gitter
    url: https://gitter.im/hexo-theme-icarus/community
    about: 与Icarus使用相关的问题请转至这里。